# Theme Settings
remote_theme: just-the-docs/just-the-docs

# Navigation Settings
# This enables the search bar in the sidebar
search_enabled: true

# Color Scheme
# Setting this to 'nil' or omitting it allows the theme 
# to follow the user's system dark/light preference.
# color_scheme: dark 

# Aux Links (Top right buttons)
aux_links:
  "Repository":
    - "https://github.com/amforth32/amforth32"

nav_external_links:
  - title: Amforth
    url: https://amforth.sourceforge.net/index.html
  - title: Forth Standard
    url: https://forth-standard.org/